# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'Smack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smack
pod 'Alamofire', '~> 4.5'
pod 'SwiftyJSON'
pod 'Socket.IO-Client-Swift'


end

  post_install do |installer|
    installer.pods_project.targets.each do |target|

      # The following is needed to ensure the "archive" step works in XCode.
      # It removes React & Yoga from the Pods project, as it is already included in the main project.
      # Without this, you'd see errors when you archive like:
      # "Multiple commands produce ... libReact.a"
      # "Multiple commands produce ... libyoga.a"

      targets_to_ignore = %w(React yoga)
      
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end

    end
  end
